project_name: nonce-encrypter
env:
  - GO111MODULE=on
release:
  prerelease: false
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm64
    - arm
  goarm:
    - 7
  flags:
    - -trimpath

archives:
- name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    bit: Arm
    bitv6: Arm6
    bitv7: Arm7
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
